### ISSUE TITLE
App not remembering logged in user

### ISSUE THREAD

**Issue by rizwankce** [leakyrelu/TaskBrewery#3]
When quite the app and re-open the app, need to log in again. It would be better to save the user login once logged in and allow the user to directly go to Tasks screen.

Bonus Feature: able to logout from app

**Comment by dopetard** [comment]
Issue resolved in commit https://github.com/leakyrelu/TaskBrewery/commit/1f39e0ef57174aa6bf68498ea90d90abfab87f1c
